import type { ChartType } from "@openvizai/shared-types";
import type { ChartEmbedding } from "./embedding.js";

export { ChartType };

/**
 * Metadata returned by the LLM alongside the chart embedding.
 *
 * Provides a human-readable title, optional subtitle, and an
 * explanation of how the LLM interpreted the user's query.
 */
export interface ChartMeta {
  /** Chart title generated by the LLM. */
  title: string;
  /** Optional subtitle (may be `null`). */
  subtitle: string | null;
  /** LLM's explanation of how it interpreted the query. */
  query_explanation: string;
}

/**
 * Complete single-chart result returned by `analyzeChart`.
 *
 * Contains the response type, metadata, and the chart payload
 * (chart_type + embedding) ready to be passed to `<OpenVizRenderer />`.
 */
export interface ChartResult {
  /** Always `"graphical"` for single-chart results. */
  response_type: "graphical";
  /** LLM-generated metadata — title, subtitle, explanation. */
  meta: ChartMeta;
  /** The chart payload. */
  chart: {
    /** Selected chart type (e.g. `"bar"`, `"line"`, `"pie"`). */
    chart_type: ChartType;
    /** Field mappings describing how data maps to visual axes. */
    embedding: ChartEmbedding;
  };
}
